#
#	SH-2 Disassembler
#
#	for Turbo-C make!
#
CC	= bcc
#
.c.obj:
	$(CC) -c -1 -O2 -f- $*.c
#
.m.obj:
	mpp $*
#
dfiles	=  dissh.obj dis.obj opcode.obj mark.obj symbol.obj
#
#  bc++4.0の場合のみ noehs.libをインクルードするよろし.
#  (exeサイズが小さくなる)
#
dissh.exe:	$(dfiles)
	$(CC) $(dfiles) noehs.lib
#	tlink @linkfile
#
#
#
#
clean	:
	del *.bak
	del *.obj
	del *.sym
#
#
